"""titles table

Revision ID: 369aa6f5dc5a
Revises: 
Create Date: 2021-05-14 19:04:06.316679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369aa6f5dc5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    op.alter_column('descriptions', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.drop_index('ft', table_name='descriptions')
    op.alter_column('titles', 'title',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('titles', 'title',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_index('ft', 'descriptions', ['title', 'description'], unique=False)
    op.alter_column('descriptions', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    op.create_table('part',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('parts_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reg_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('inv_number', mysql.TEXT(), nullable=True),
    sa.Column('gik_number', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('obtaining_way_id', mysql.FLOAT(), nullable=True),
    sa.Column('obtaining_source', mysql.TEXT(), nullable=True),
    sa.Column('reg_reason_id', mysql.FLOAT(), nullable=True),
    sa.Column('width', mysql.FLOAT(), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=True),
    sa.Column('dim_str', mysql.TEXT(), nullable=True),
    sa.Column('start_date', mysql.TEXT(), nullable=True),
    sa.Column('precision_time', mysql.TEXT(), nullable=True),
    sa.Column('period_str', mysql.TEXT(), nullable=True),
    sa.Column('create_date', mysql.TEXT(), nullable=True),
    sa.Column('modify_date', mysql.TEXT(), nullable=True),
    sa.Column('reg_date', mysql.TEXT(), nullable=True),
    sa.Column('imported', mysql.TEXT(), nullable=True),
    sa.Column('act_number_corr', mysql.TEXT(), nullable=True),
    sa.Column('dim_corr', mysql.TEXT(), nullable=True),
    sa.Column('weight_corr', mysql.TEXT(), nullable=True),
    sa.Column('gik_date', sa.DATE(), nullable=True),
    sa.Column('authors', mysql.TEXT(), nullable=True),
    sa.Column('technologies', mysql.TEXT(), nullable=True),
    sa.Column('precision_ordinal', mysql.FLOAT(), nullable=True),
    sa.Column('main_words', mysql.TEXT(), nullable=True),
    sa.Column('typology_desc', mysql.TEXT(), nullable=True),
    sa.Column('length', mysql.FLOAT(), nullable=True),
    sa.Column('ext_exhibit_id', mysql.TEXT(), nullable=True),
    sa.Column('pub_limit_date', mysql.FLOAT(), nullable=True),
    sa.Column('efzk', mysql.TEXT(), nullable=True),
    sa.Column('act_number', mysql.TEXT(), nullable=True),
    sa.Column('production_place', mysql.TEXT(), nullable=True),
    sa.Column('find_place', mysql.TEXT(), nullable=True),
    sa.Column('provenance', mysql.TEXT(), nullable=True),
    sa.Column('finish_date', mysql.TEXT(), nullable=True),
    sa.Column('spec_number', mysql.TEXT(), nullable=True),
    sa.Column('order_number', mysql.TEXT(), nullable=True),
    sa.Column('weight_str', mysql.TEXT(), nullable=True),
    sa.Column('read_only', mysql.TEXT(), nullable=True),
    sa.Column('order_date', mysql.TEXT(), nullable=True),
    sa.Column('ext_url', mysql.TEXT(), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('museum_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('museum_name', mysql.TEXT(), nullable=True),
    sa.Column('museum_code', mysql.FLOAT(), nullable=True),
    sa.Column('museum_class_id', mysql.FLOAT(), nullable=True),
    sa.Column('museum_uin', mysql.FLOAT(), nullable=True),
    sa.Column('museum_inn', mysql.FLOAT(), nullable=True),
    sa.Column('museum_correctable', mysql.TEXT(), nullable=True),
    sa.Column('museum_parent_id', mysql.FLOAT(), nullable=True),
    sa.Column('museum_country_code', mysql.TEXT(), nullable=True),
    sa.Column('museum_umbrella_org_id', mysql.FLOAT(), nullable=True),
    sa.Column('museum_full_uin', mysql.TEXT(), nullable=True),
    sa.Column('typology_id', mysql.FLOAT(), nullable=True),
    sa.Column('typology_name', mysql.TEXT(), nullable=True),
    sa.Column('typology_obsolete', mysql.TEXT(), nullable=True),
    sa.Column('typology_code', mysql.FLOAT(), nullable=True),
    sa.Column('category_id', mysql.FLOAT(), nullable=True),
    sa.Column('category_name', mysql.FLOAT(), nullable=True),
    sa.Column('category_code', mysql.FLOAT(), nullable=True),
    sa.Column('dim_unit_id', mysql.FLOAT(), nullable=True),
    sa.Column('dim_unit_name', mysql.TEXT(), nullable=True),
    sa.Column('ownership_id', mysql.FLOAT(), nullable=True),
    sa.Column('ownership_name', mysql.TEXT(), nullable=True),
    sa.Column('budget_id', mysql.FLOAT(), nullable=True),
    sa.Column('budget_name', mysql.TEXT(), nullable=True),
    sa.Column('ext_system_id', mysql.FLOAT(), nullable=True),
    sa.Column('weight_unit_id', mysql.FLOAT(), nullable=True),
    sa.Column('weight_unit_name', mysql.TEXT(), nullable=True),
    mariadb_default_charset='utf8',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
